# PROTOTYPE
# These types are meant to be generated based on the content model.

DomainContent:
    type: "interface"
    config:
        fields:
            _info:
                description: "Item's content info"
                type: Content
            _content:
                description: "Underlying content item"
                type: Content
                deprecationReason: "Renamed to _info"
            _type:
                description: "Item's content type"
                type: ContentType
            _location:
                description: "The content's main location"
                type: Location
            _allLocations:
                description: "All the content's locations"
                type: "[Location]"
            _name:
                description: "The content item's name, in the prioritized language(s), based on the object name pattern"
                type: String
            _url:
                description: "The content item's url alias, based on the main location."
                type: String
            _thumbnail:
                type: Thumbnail
        resolveType: "@=resolver('DomainContentType', [value])"

AbstractDomainContent:
    type: "object"
    config:
        fields:
            id:
                type: "ID!"
                builder: Relay::GlobalId
                builderConfig:
                    typeName: DomainContent
                description: "The Content item's unique ID."
            _type:
                description: "The item's Content type"
                type: ContentType
                resolve: '@=resolver("ContentTypeById", [value.contentInfo.contentTypeId])'
            _content:
                description: 'Underlying content info item'
                type: Content
                resolve: '@=value.contentInfo'
                deprecationReason: "Renamed to _info"
            _info:
                description: 'Underlying content info item'
                type: Content
                resolve: '@=value.contentInfo'
            _location:
                description: 'Main location'
                type: Location
                resolve: '@=resolver("LocationById", [value.contentInfo.mainLocationId])'
            _allLocations:
                description: 'All the locations'
                type: '[Location]'
                resolve: '@=resolver("LocationsByContentId", [value.contentInfo.id])'
            _name:
                description: "The content item's name, in the prioritized language(s), based on the object name pattern"
                type: String
                resolve: "@=value.getName()"
            _url:
                description: "The content item's url alias, based on the main location."
                type: String
                resolve: "@=resolver('MainUrlAlias', [value])"
            _thumbnail:
                type: Thumbnail
                resolve: "@=resolver('ContentThumbnail', [value])"

UntypedContent:
    type: object
    inherits:
        - AbstractDomainContent
    config:
        interfaces:
            - DomainContent
            - Node
        fields:
            reason:
                type: String
                resolve: "This content type isn't part of the schema."

DomainContentTypeGroup:
    type: object
    config:
        fields:
            _info:
                type: ContentTypeGroup
                description: "The contenttype group's properties"
                resolve: "@=value"
            _types:
                type: DomainGroupContentTypes
                description: "Content types from this group"

DomainContentType:
    type: interface
    config:
        fields:
            _info:
                type: ContentType
                description: "The content type's properties"

BaseDomainContentType:
    type: object
    config:
        fields:
            _info:
                type: ContentType
                resolve: "@=value"

DomainContentByIdentifierConnection:
    type: relay-connection
    config:
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String

Thumbnail:
    type: object
    config:
        fields:
            uri:
                type: String
                description: "The image's URI (example: 'https://example.com/var/site/storage/images/_aliases/small/9/8/1/0/189-1-eng-GB/image.png')"
            width:
                type: Int
                description: "The width as number of pixels (example: 320)"
            height:
                type: Int
                description: "The height as number of pixels (example: 200)"
            alternativeText:
                type: String