services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "Location", method: "resolveLocation" }
            - { name: overblog_graphql.resolver, alias: "LocationById", method: "resolveLocationById" }
            - { name: overblog_graphql.resolver, alias: "LocationChildren", method: "resolveLocationChildren" }
            - { name: overblog_graphql.resolver, alias: "LocationsByContentId", method: "resolveLocationsByContentId" }
        arguments:
            $locationService: '@ezpublish.siteaccessaware.service.location'
            $contentService: '@ezpublish.siteaccessaware.service.content'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ContentResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "Content", method: "resolveContent" }
            - { name: overblog_graphql.resolver, alias: "ContentById", method: "resolveContentById" }
            - { name: overblog_graphql.resolver, alias: "ContentByIdList", method: "resolveContentByIdList" }
            - { name: overblog_graphql.resolver, alias: "ContentVersions", method: "resolveContentVersions" }
            - { name: overblog_graphql.resolver, alias: "ContentByType", method: "findContentByType" }
            - { name: overblog_graphql.resolver, alias: "ContentRelations", method: "findContentRelations" }
            - { name: overblog_graphql.resolver, alias: "ContentReverseRelations", method: "findContentReverseRelations" }
            - { name: overblog_graphql.resolver, alias: "CurrentVersion", method: "resolveCurrentVersion" }
        arguments:
            $contentService: '@ezpublish.siteaccessaware.service.content'
            $searchService: '@ezpublish.siteaccessaware.service.search'
            $contentTypeService: '@ezpublish.siteaccessaware.service.content_type'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\DomainContentResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DomainContentItemsByTypeIdentifier", method: "resolveDomainContentItems" }
            - { name: overblog_graphql.resolver, alias: "DomainFieldValue", method: "resolveDomainFieldValue" }
            - { name: overblog_graphql.resolver, alias: "DomainContentType", method: "resolveDomainContentType" }
            - { name: overblog_graphql.resolver, alias: "DomainContentItem", method: "resolveDomainContentItem" }
            - { name: overblog_graphql.resolver, alias: "DomainRelationFieldValue", method: "resolveDomainRelationFieldValue" }
            - { name: overblog_graphql.resolver, alias: "MainUrlAlias", method: "resolveMainUrlAlias" }
        arguments:
            $repository: "@ezpublish.siteaccessaware.repository"

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ContentThumbnailResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "ContentThumbnail", method: "resolveContentThumbnail" }
        arguments:
            $imageFieldType: "@ezpublish.fieldType.ezimage"
            $variationHandler: "@ezpublish.fieldType.ezimage.variation_service"

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\UploadFiles:
        arguments:
            $repository: '@ezpublish.siteaccessaware.repository'
        tags:
            - { name: overblog_graphql.mutation, alias: "UploadFiles", method: "uploadFiles" }

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\UserResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "User", method: "resolveUser" }
            - { name: overblog_graphql.resolver, alias: "UserGroups", method: "resolveUserGroups" }
            - { name: overblog_graphql.resolver, alias: "UserById", method: "resolveUserById" }
            - { name: overblog_graphql.resolver, alias: "UserGroupsByUserId", method: "resolveUserGroupsByUserId" }
            - { name: overblog_graphql.resolver, alias: "UserGroupById", method: "resolveUserGroupById" }
            - { name: overblog_graphql.resolver, alias: "UserGroupSubGroups", method: "resolveUserGroupSubGroups" }
            - { name: overblog_graphql.resolver, alias: "UsersOfGroup", method: "resolveUsersOfGroup" }

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ContentTypeResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "ContentTypeById", method: "resolveContentTypeById" }
            - { name: overblog_graphql.resolver, alias: "ContentType", method: "resolveContentType" }
            - { name: overblog_graphql.resolver, alias: "ContentTypesFromGroup", method: "resolveContentTypesFromGroup" }
            - { name: overblog_graphql.resolver, alias: "ContentTypeGroupByIdentifier", method: "resolveContentTypeGroupByIdentifier" }
        arguments:
            $contentTypeService: '@ezpublish.siteaccessaware.service.content_type'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\FieldDefinitionResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "FieldDefinitionName", method: "resolveFieldDefinitionName" }
            - { name: overblog_graphql.resolver, alias: "FieldDefinitionDescription", method: "resolveFieldDefinitionDescription" }
            - { name: overblog_graphql.resolver, alias: "SelectionFieldDefinitionOptions", method: "resolveSelectionFieldDefinitionOptions" }

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\SectionResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SectionById", method: "resolveSectionById" }
        arguments:
            $sectionService: '@ezpublish.siteaccessaware.service.section'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\UrlAliasResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "UrlAliasType", method: "resolveUrlAliasType" }
            - { name: overblog_graphql.resolver, alias: "LocationUrlAliases", method: "resolveLocationUrlAliases" }
        arguments:
            $urlAliasService: '@ezpublish.siteaccessaware.service.url_alias'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\SearchResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SearchContent", method: "searchContent" }
            - { name: overblog_graphql.resolver, alias: "SearchContentOfTypeAsConnection", method: "searchContentOfTypeAsConnection" }
        arguments:
            $searchService: '@ezpublish.siteaccessaware.service.search'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\RichTextResolver:
        arguments:
            - "@ezrichtext.converter.output.xhtml5"
            - "@ezrichtext.converter.edit.xhtml5"
        tags:
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToHtml5", method: "xmlToHtml5" }
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToHtml5Edit", method: "xmlToHtml5Edit" }
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToPlainText", method: "xmlToplainText" }

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ImageFieldResolver:
        arguments:
            $imageFieldType: "@ezpublish.fieldType.ezimage"
            $variationHandler: "@ezpublish.fieldType.ezimage.variation_service"
            $contentService: "@ezpublish.siteaccessaware.service.content"
            $variations: "$image_variations$"
        tags:
            - { name: overblog_graphql.resolver, alias: "ImageVariations", method: "resolveImageVariations" }
            - { name: overblog_graphql.resolver, alias: "ImageVariation", method: "resolveImageVariation" }

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\DateResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DateTimeFormat", method: "resolveDateToFormat"}

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ImageAssetFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DomainImageAssetFieldValue", method: "resolveDomainImageAssetFieldValue"}

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\SelectionFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SelectionFieldValue", method: "resolveSelectionFieldValue"}

    EzSystems\EzPlatformGraphQL\GraphQL\Relay\NodeResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "node", method: "resolveNode" }
            - { name: overblog_graphql.resolver, alias: "node_type", method: "resolveType" }

    EzSystems\EzPlatformGraphQL\GraphQL\Relay\SearchResolver:
        tags:
            - {name: overblog_graphql.resolver, alias: "SearchContentConnection", method: "searchContent"}

    #
    # Object States
    #

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ObjectStateGroupResolver:
        arguments:
            $objectStateService: '@ezpublish.siteaccessaware.service.object_state'
        tags:
            - {name: overblog_graphql.resolver, alias: "ObjectStateGroupById", method: "resolveObjectStateGroupById"}
            - {name: overblog_graphql.resolver, alias: "ObjectStateGroups", method: "resolveObjectStateGroups"}

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\ObjectStateResolver:
        arguments:
            $objectStateService: '@ezpublish.siteaccessaware.service.object_state'
        tags:
            - {name: overblog_graphql.resolver, alias: "ObjectStateById", method: "resolveObjectStateById"}
            - {name: overblog_graphql.resolver, alias: "ObjectStateByContentInfo", method: "resolveObjectStateByContentInfo"}
            - {name: overblog_graphql.resolver, alias: "ObjectStatesByGroup", method: "resolveObjectStatesByGroup"}
            - {name: overblog_graphql.resolver, alias: "ObjectStatesByGroupId", method: "resolveObjectStatesByGroupId"}

    #
    # Content mutations
    #
    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\DomainContentMutationResolver:
        tags:
            - { name: overblog_graphql.mutation, alias: "CreateDomainContent", method: "createDomainContent" }
            - { name: overblog_graphql.mutation, alias: "DeleteDomainContent", method: "deleteDomainContent" }
            - { name: overblog_graphql.mutation, alias: "UpdateDomainContent", method: "updateDomainContent" }

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\Map\UploadMap: ~
