services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\LocationResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "Location", method: "resolveLocation" }
            - { name: overblog_graphql.resolver, alias: "LocationById", method: "resolveLocationById" }
            - { name: overblog_graphql.resolver, alias: "LocationChildren", method: "resolveLocationChildren" }
            - { name: overblog_graphql.resolver, alias: "LocationsByContentId", method: "resolveLocationsByContentId" }
        arguments:
            $locationService: '@ezpublish.siteaccessaware.service.location'
            $contentService: '@ezpublish.siteaccessaware.service.content'

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\ContentResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "Content", method: "resolveContent" }
            - { name: overblog_graphql.resolver, alias: "ContentFields", method: "resolveContentFields" }
            - { name: overblog_graphql.resolver, alias: "ContentById", method: "resolveContentById" }
            - { name: overblog_graphql.resolver, alias: "ContentByIdList", method: "resolveContentByIdList" }
            - { name: overblog_graphql.resolver, alias: "ContentVersions", method: "resolveContentVersions" }
            - { name: overblog_graphql.resolver, alias: "ContentFieldsInVersion", method: "resolveContentFieldsInVersion" }
            - { name: overblog_graphql.resolver, alias: "ContentByType", method: "findContentByType" }
            - { name: overblog_graphql.resolver, alias: "ContentRelations", method: "findContentRelations" }
            - { name: overblog_graphql.resolver, alias: "ContentReverseRelations", method: "findContentReverseRelations" }
            - { name: overblog_graphql.resolver, alias: "FieldValueType", method: "resolveFieldValueType" }
        arguments:
            $contentService: '@ezpublish.siteaccessaware.service.content'
            $searchService: '@ezpublish.siteaccessaware.service.search'
            $contentTypeService: '@ezpublish.siteaccessaware.service.content_type'

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\FieldValueHtmlResolver:
        arguments:
            - "@ezpublish.twig.extension.field_rendering"
        tags:
            - { name: overblog_graphql.resolver, alias: "FieldValueToHtml", method: "resolveFieldValueToHtml" }

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\DomainContentResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DomainContentItemsByTypeIdentifier", method: "resolveDomainContentItems" }
            - { name: overblog_graphql.resolver, alias: "DomainFieldValue", method: "resolveDomainFieldValue" }
            - { name: overblog_graphql.resolver, alias: "DomainContentType", method: "resolveDomainContentType" }
            - { name: overblog_graphql.resolver, alias: "DomainContentItem", method: "resolveDomainContentItem" }
            - { name: overblog_graphql.resolver, alias: "DomainRelationFieldValue", method: "resolveDomainRelationFieldValue" }
        arguments:
            $repository: "@ezpublish.siteaccessaware.repository"

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\UserResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "User", method: "resolveUser" }
            - { name: overblog_graphql.resolver, alias: "UserGroups", method: "resolveUserGroups" }
            #- { name: overblog_graphql.resolver, alias: "UserFields", method: "resolveUserFields" }
            - { name: overblog_graphql.resolver, alias: "UserById", method: "resolveUserById" }
            - { name: overblog_graphql.resolver, alias: "UserGroupsByUserId", method: "resolveUserGroupsByUserId" }
            - { name: overblog_graphql.resolver, alias: "UserGroupById", method: "resolveUserGroupById" }
            - { name: overblog_graphql.resolver, alias: "UserGroupSubGroups", method: "resolveUserGroupSubGroups" }
            - { name: overblog_graphql.resolver, alias: "UsersOfGroup", method: "resolveUsersOfGroup" }

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\ContentTypeResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "ContentTypeById", method: "resolveContentTypeById" }
            - { name: overblog_graphql.resolver, alias: "ContentType", method: "resolveContentType" }
            - { name: overblog_graphql.resolver, alias: "ContentTypesFromGroup", method: "resolveContentTypesFromGroup" }
            - { name: overblog_graphql.resolver, alias: "ContentTypeGroupsFromContentType", method: "resolveGroupsFromContentType" }
            - { name: overblog_graphql.resolver, alias: "ContentTypeGroupByIdentifier", method: "resolveContentTypeGroupByIdentifier" }
        arguments:
            $contentTypeService: '@ezpublish.siteaccessaware.service.content_type'

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\FieldDefinitionResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "FieldDefinitionName", method: "resolveFieldDefinitionName" }
            - { name: overblog_graphql.resolver, alias: "FieldDefinitionDescription", method: "resolveFieldDefinitionDescription" }
            - { name: overblog_graphql.resolver, alias: "SelectionFieldDefinitionOptions", method: "resolveSelectionFieldDefinitionOptions" }

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\SectionResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SectionById", method: "resolveSectionById" }
        arguments:
            $sectionService: '@ezpublish.siteaccessaware.service.section'

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\UrlAliasResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "UrlAliasType", method: "resolveUrlAliasType" }
            - { name: overblog_graphql.resolver, alias: "LocationUrlAliases", method: "resolveLocationUrlAliases" }
        arguments:
            $urlAliasService: '@ezpublish.siteaccessaware.service.url_alias'

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\SearchResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SearchContent", method: "searchContent" }
        arguments:
            $searchService: '@ezpublish.siteaccessaware.service.search'

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\RichTextResolver:
        arguments:
            - "@ezpublish.fieldType.ezrichtext.converter.output.xhtml5"
            - "@ezpublish.fieldType.ezrichtext.converter.edit.xhtml5"
        tags:
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToHtml5", method: "xmlToHtml5" }
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToHtml5Edit", method: "xmlToHtml5Edit" }

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\ImageFieldResolver:
        arguments:
            $imageFieldType: "@ezpublish.fieldType.ezimage"
            $variationHandler: "@ezpublish.fieldType.ezimage.variation_service"
            $contentService: "@ezpublish.siteaccessaware.service.content"
            $variations: "$image_variations$"
        tags:
            - { name: overblog_graphql.resolver, alias: "ImageVariations", method: "resolveImageVariations" }
            - { name: overblog_graphql.resolver, alias: "ImageVariation", method: "resolveImageVariation" }

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\DateResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DateTimeFormat", method: "resolveDateToFormat"}

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\ImageAssetFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DomainImageAssetFieldValue", method: "resolveDomainImageAssetFieldValue"}

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\SelectionFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SelectionFieldValue", method: "resolveSelectionFieldValue"}
