services:
    bd_ezplatform_graphql.command.generate_platform_domain_schema:
        autoconfigure: true
        autowire: true
        class: BD\EzPlatformGraphQLBundle\Command\GeneratePlatformDomainTypesCommand
        arguments:
            - "@ezpublish.api.repository"
        tags:
            -  { name: console.command }

    BD\EzPlatformGraphQLBundle\GraphQL\TypeDefinition\ContentTypeMapper: ~


    bd_ezplatform_graphql.graph.mutation.section:
        class: BD\EzPlatformGraphQLBundle\GraphQL\Mutation\SectionMutation
        arguments:
            - "@ezpublish.api.service.section"
        tags:
            - { name: "overblog_graphql.mutation", alias: "CreateSection", method: "createSection" }
            - { name: "overblog_graphql.mutation", alias: "DeleteSection", method: "deleteSection" }

    BD\EzPlatformGraphQLBundle\GraphQL\InputMapper\SearchQueryMapper: ~
